### ISSUE TITLE
Some strings are not between parentheses

### ISSUE THREAD

**Issue by FvD** [leanpub/translations#2]
I notice that some strings do not have parentheses. From line 80  to 83 in the nl.yml for example:

```
  w_charge_card: "Betaal met creditcard"
  w_coming_soon: Binnenkort
  w_comments: "Reacties"
  w_complete: Compleet
```

Since this also happens in the en.yml there must be a reason and I will leave them unchanged. However some instruction to translators in the README about this would be welcome.

**Comment by peterarmstrong** [comment]
This was just sloppiness on our part.  We will resolve this as we overhaul the language files.  Sorry for missing this issue, btw.
