### ISSUE TITLE
de.yml not used?

### ISSUE THREAD

**Issue by winniehell** [leanpub/translations#9]
The [current de.yml](https://github.com/leanpub/translations/blob/master/de.yml#L251) contains the correct text `... unterstützt den Autor ...`.

Nevertheless, the generated book does not:
![error](https://cloud.githubusercontent.com/assets/1652293/9802432/6b1471d8-581a-11e5-9f51-d85ec5ad8231.png)
(`... unterstützt de Autor ...`)

Is this still taken from [here](https://github.com/lenepp/leanpub_localization/blob/master/de.yml#L189)?

**Comment by lenepp** [comment]
We have corrected this, thanks.
